### ISSUE TITLE
Deps vs dev deps

### ISSUE THREAD

**Issue by byrnedo** [cybertoothca/ember-cli-textarea-autosize#18]
Hi, 
Shouldn't autosize and ember-cli-text-support-mixins be in dependencies, not dev dependencies?
Or maybe I don't understand how that works.
I just tried updating from the bower-tied version to the newest and I had to add those deps manually in my package.json.

Edit: for instance https://github.com/kennethkalmer/ember-cli-nouislider/blob/master/package.json has no-ui-slider in deps now that it's moved to npm as well.

**Comment by nadnoslen** [comment]
Hey @byrnedo, I must apologize...I just saw this issue last night.  Let me see if I can reproduce your experience and I'll double check these dependencies to offer an explanation.  Thanks for your feedback.

**Comment by nadnoslen** [comment]
Hey again @byrnedo,

In all of my projects I haven't experienced any issues using `devDependencies`.  I've just kind of kept with what others have been doing.

As for your upgrade experience, I fear I did a poor job of setting you up for success.  Ideally you should have been instructed to simply run `ember install ember-cli-textarea-autosize` from the root of your application.  That single command does two very important things behind the curtain:

1. It performs a `npm install --save-dev ember-cli-textarea-autosize`.
2. `ember generate ember-cli-textarea-autosize` is called which fires the default add-on blueprint.  This blueprint (found [here](https://github.com/cybertoothca/ember-cli-textarea-autosize/blob/master/blueprints/ember-cli-textarea-autosize/index.js)) will auto-magically install the `autosize` npm package and the `ember-cli-text-support-mixins` ember-add-on.  You'll then see them appended to your `devDependencies` in your project's `package.json`.

I am assuming you simply changed the `ember-cli-textarea-autosize`'s version in your `package.json` and then ran a quick `npm install`.  All that does is upgrade `ember-cli-textarea-autosize` to the version you specified in your `package.json`.  What you need is that blueprint to now fire installing the dependencies.

**I'd say for pretty much every ember add-on in your project, you should always run the `ember install [NAME]` to upgrade it.  That will always run the two very important steps I refer to above.**

(I even go as far as to record in a separate file at the root of my project all of the Ember add-on's that I've installed.  That way when a do a full-blown Ember-CLI upgrade I know which add-ons I need to re-install; [here's an example of that technique for this particular add-on](https://github.com/cybertoothca/ember-cli-textarea-autosize/blob/master/install_ember_addons.sh)).

Sorry once again for my terrible response time.

**Comment by byrnedo** [comment]
Hi @nadnoslen,

No worries at all. Ah ok, I get you, I didn't realise that with having to run `ember install` every time. I had updated the package.js version like you said. Thanks for the thorough answer!
