### ISSUE TITLE
Autogrow auto shrink

### ISSUE THREAD

**Issue by mariobrosch** [cybertoothca/ember-cli-textarea-autosize#20]
Hi, I use the autogrow on a form. The form submit perfectly, but doesnt causes a refresh of the page. How can I shrink the textarea back to its original size?

**Comment by nadnoslen** [comment]
Hey @mariobrosch,
Once your form's contents is submitted and saved, consider clearing the property/value that you assigned to the `{{textarea-autosize ...}}` component.  Doing so will cause the textarea to go back to it's original size.

Does that make sense?

**Comment by mariobrosch** [comment]
Well, that makes sense, but doesnt work in my situation. Is it possible that it doesnt work because I extended the textareaautosize?

**Comment by mariobrosch** [comment]
fixed the issue. Problem was that I had a binded property to the textarea. I changed the property but didnt trigger the autosize.update. Manually trigger the update on the textarea also didn't work. Directly setting the value to the textarea works.

Example of code:
```
const textAreaAutoGrow = document.querySelector('textarea[name="new-message"]');
textAreaAutoGrow.value = '';
autosize.update(textAreaAutoGrow);
```

**Comment by nadnoslen** [comment]
Interesting...  I'm glad you got it to work.  I'm kind of surprised you'd have to go through that much trouble.  Must be an interesting use-case.  Cheers Mario...let me know if you have any other challenges.
