### ISSUE TITLE
Doesn't grow on load

### ISSUE THREAD

**Issue by ryukra** [cybertoothca/ember-cli-textarea-autosize#21]
The first time I load the size the textarea isn't already grown.
I create the textarea in an component within a {{#each}}

**Comment by nadnoslen** [comment]
I'll take a look.  This little addon is due for some Ember-Cli upgrade love anyway.  Thanks @ryukra.  On it.

**Comment by nadnoslen** [comment]
Hey @ryukra,

I started doing some upgrading yesterday on this addon.  I should have it into Ember-3-land very soon.

Shoot me a few more details:
1. What browsers are you experiencing this behaviour?
1. How long ago did you install this addon?
1. What version of Ember are you using?
1. If you can, check your `node_modules/autosize/package.json` - what version of autosize.js do you have?

One thing you can try is to re-run the addon's blueprint:

```bash
$ ember g ember-cli-textarea-autosize
```

That might help?

**Comment by nadnoslen** [comment]
Have released a new version of the addon.  Run `ember install ember-cli-textarea-autosize` to grab the latest.

The most important thing that will happen is that the `autosize` library will be updated.  This might fix your issues.
